name = "sysimg"
uuid = "b12093e7-5151-42d4-b49b-cf14d741782e"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"

[compat]
Colors = "0.13.1"
