name = "AppEnv"
uuid = "9f11263e-cf0d-4932-bae6-807953dbea74"
authors = ["Janis Erdmanis <janiserdmanis@protonmail.ch>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]